### PR TITLE
Fix loading screen & add extra validations during initial loading

### LINKED ISSUE #106: Error for uncertified user trying to submit metadata

### PR DESCRIPTION
**Pull request by rrchai**
- fixes #106
- improve the loading screen function
  - add checkpoints on permission to fileview and certification of users
  - change 'login' to 'landing'
- fixes: tryCatch not prevent app from crashing and show proper loading screen

### CODE REVIEW

File: functions/dcWaiter.R [hunk 1]
```diff
@@ -31,28 +33,49 @@ dcWaiter <- function(stage = c("show", "update", "hide"),
...
-        h3(sprintf("Welcome, %s!", usrName))
+        h3("Looks like you're not a certified synapse user!"),
+        span("Please follow the ", 
+          a("instruction", 
+            href = "https://help.synapse.org/docs/User-Account-Tiers.2007072795.html#UserAccountTiers-CertifiedUsers", 
+            target = "_blank"
+          ),
+          " to become a certified user, then refresh this page."
+        )
+      ))
```
Comment (rrchai) [inline functions/dcWaiter.R:58]: @milen-sage 

Since I was improving the initial loading (landing) screen, the approach in this pr is to stop users to see the app if they are not certified synapse users. It will stop at a loading screen and redirect users to certify.

But if you prefer that uncertified users still be able to use the app, I can just add validation before the submission.

File: functions/dcWaiter.R [hunk 2]
```diff
@@ -31,28 +33,49 @@ dcWaiter <- function(stage = c("show", "update", "hide"),
...
+    } else if (!isPermission) {
+      # when user is not certified synapse user
+      waiter_update(html = tagList(
+        img(src = "img/synapse_logo.png", height = "120px"),
+        h3("Looks like you dont have access to fileview"),
+        span("placeholder ...")
```
Comment (rrchai) [inline functions/dcWaiter.R:64]: @milen-sage I need your help on this one.

My testing account do not have access to the filevie. I will get this error and app will crash:
```
Warning: Error in py_call_impl: AccessCredentialsError: Your access to 'syn20446927'' could not be resolved. Please check your credentials and try again.

Detailed traceback:
File "/home/rchai/miniconda3/envs/data_curator_dev_env/lib/python3.7/site-packages/schematic/store/synapse.py", line 83, in **init**
raise AccessCredentialsError(self.storageFileview)
```

I would like to prevent the app crash and show the error message in the initial loading screen. It could possibly happen if users not have access to fileview?

The approach I added here is to notify that they don't have access to the fileview, but I don't know what description/instructions to help them solve this issue. 

preview
--- 
Screen Shot 2021-11-17 at 10 57 24 AM

**Comment by milen-sage** [comment]
@rrchai thanks! This will be a pretty useful screen for users that don't have access. Can we have a message along the lines of 

`Looks like you don't have sufficient permissions for curation. Please contact your team and project administrators.`

**Comment by milen-sage** [comment]
@ychae could you take a look if this makes sense from a user perspective?

**Comment by ychae** [comment]
@milen-sage Just to make sure I understand what this PR accomplishes:
1. Checks to see if the user is Certified on Synapse. If true, they'll continue to the data annotation process. If false, the user will be directed to go certify their account immediately after the loading screen. 
2. Checks to see if the user has sufficient permissions to access the files and folders and projects necessary for curation. If true, the user continues on with the data annotation process. If false, the user is directed to contact someone to be granted the necessary permissions. 

@rrchai I like the language that Milen suggested for the permissions issue. For the certification notification, could we say: `It looks like you're not a Certified User on Synapse. Please follow these instructions (the link that you have) to become a Certified User. Once you're certified, return here and refresh this page.`

**Comment by ychae** [comment]
@milen-sage To actually answer your question, if my understanding above in points 1 and 2 are correct, it seems like a great addition to improve usability and user experience!

**Comment by milen-sage** [comment]
Thanks for pointing out the distinction between the user access and user certification @ychae! This makes a lot of sense. 

Agreed - this PR overall would avoid a lot of explanation and debugging we otherwise have to do w/ users.
