### PR TITLE
Fix: cannot combine mismatch types and empty file errors in validation 

### LINKED ISSUE #369: MC2 DCA: Unable to validate PersonView manifest
**Describe the bug**
Currently experiencing issues with validating a PersonView manifest.  To help with debugging, I reduced the manifest to a single row and received the following logs:

```
2022-06-17T04:48:20.283805+00:00 shinyapps[5992584]: ERROR: [2022-06-17 04:48:19] root - For attribute Person Grant Number in row 2 it does not appear as if you provided a comma delimited string. Please check your entry ('Not Associated'') and try again.
2022-06-17T04:48:20.283870+00:00 shinyapps[5992584]: ERROR: [2022-06-17 04:48:19] root - For attribute Person Consortium Name in row 2 it does not appear as if you provided a comma delimited string. Please check your entry ('PS-ON'') and try again.
2022-06-17T04:48:20.283926+00:00 shinyapps[5992584]: ERROR: [2022-06-17 04:48:20] root - For attribute Working Group Participation in row 2 it does not appear as if you provided a comma delimited string. Please check your entry ('Cell and Tissue Mechanics'') and try again.
2022-06-17T04:48:20.283975+00:00 shinyapps[5992584]: ERROR: [2022-06-17 04:48:20] root - For attribute Chair Roles in row 2 it does not appear as if you provided a comma delimited string. Please check your entry ('None'') and try again.
2022-06-17T04:48:20.284022+00:00 shinyapps[5992584]: Warning: Error in bind_rows: Can't combine `..1$Column` <character> and `..5$Column` <integer>.
2022-06-17T04:48:20.284086+00:00 shinyapps[5992584]:   [No stack trace available]
```

@brynnz22 was able to successfully validate the manifest using schematic CLI; ergo, the conclusion is that the error is with the DCA.

**To Reproduce**
1. Go to [the DCA](https://sagebio.shinyapps.io/csbc_data_curator_staging/) > **Submit & Validate Metadata**
2. In the **Selection** bar up top, select "CCKP- MC2 Admin" for Project, "people" for Folder, and "Person View" for template. Apply the changes by clicking on :arrows_counterclockwise:
3. Upload the [PersonView manifest](https://docs.google.com/spreadsheets/d/1_havAEvHe3FYjXaPLGkxpSqYLIR6PAYztn_0B0z5NDA/edit#gid=0) as a CSV > **Validate Metadata**
4. See error (hidden under the Waiter window)

https://user-images.githubusercontent.com/9377970/174228466-90f71e52-a2c6-42d8-a3c6-42ddd2786833.mov

**Priority** (select one)
- [ ] Minor ⬇️
- [x] Major 📢
- [ ] Critical 🆘

### LINKED ISSUE #370: Invalid error messages for empty file
**Describe the bug**

When no files uploaded, "out-of-date" error was shown.

**To Reproduce**

empty-file-bug

**Expected behavior**

Should display empty file message

**Priority** (select one)
- [x] Major 📢

### PR DESCRIPTION
**Pull request by rrchai**
- fixes #369 
- fixes #370

This is a hotfix, which will be merged directly to main and then update develop.

### CODE REVIEW

File: functions/validationResult.R [hunk 1]
```diff
@@ -8,21 +8,21 @@ validationResult <- function(anno.res, template, manifest) {
...
-  # in case there are some errors we haven't captured
-  if (is.null(anno.res)) {
+  # if no uploaded manifest or empty manifest
+  if (is.null(manifest) || nrow(manifest) == 0) {
     return(list(
       result = "invalid",
-      error_type = "Out of Date",
-      error_msg = "Something went wrong while validating your manifest. Please contact administrator."
+      error_type = "Empty File",
+      error_msg = "Please <b>upload</b> a filled template !"
```
Comment (milen-sage) [inline functions/validationResult.R:16]: filled -> filled in

File: functions/validationResult.R [hunk 2]
```diff
@@ -8,21 +8,21 @@ validationResult <- function(anno.res, template, manifest) {
...
 
-  # if no uploaded manifest or empty manifest
-  if (is.null(manifest) || nrow(manifest) == 0) {
+  # in case there are some errors we haven't captured
+  if (is.null(anno.res)) {
     return(list(
       result = "invalid",
-      error_type = "Empty File",
-      error_msg = "Please <b>upload</b> a filled template !"
+      error_type = "Out of Date",
```
Comment (milen-sage) [inline functions/validationResult.R:24]: How flexible is the name of this error_type? Since this is a hot fix the "out of date" type is fine, but we probably want something more generic in general.

File: functions/validationResult.R [hunk 3]
```diff
@@ -8,21 +8,21 @@ validationResult <- function(anno.res, template, manifest) {
...
+      error_msg = "Something went wrong while validating your manifest. Please contact administrator."
```
Comment (milen-sage) [inline functions/validationResult.R:25]: administrator -> your DCC staff.

**Review by milen-sage — APPROVED** [review]

File: functions/validationResult.R (hunk 2 above)
Comment (rrchai) [reply functions/validationResult.R:24]: This error is occurred when the validationModelManifest failed and used to prevent the app from crashing. It was not always clear what the errors were coming from. It could be the the data type they choose from dropdown is invalid for validation anymore, or new incompatible errors with updated schematic. 

The `error_type` is display on the waiter screen after the validation completes, before they can see the actual `error_msg`. I agree to improve the error type for this scenario to a more generic language in the future.
